version: '3'
services:
  website:
    image: advent-website
    container_name: advent-website
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/logs/website:/srv/logs
  day01:
    image: day01
    container_name: day01
    ports:
      - "1:1"
      - "11111:11111"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -H \"Cookie2: XMAS=supersecretstuffhere\" localhost:11111 | grep -q BJKFPdZ8o0Rw9dgDiv4Mb1cJ9YknSBvX || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  day02:
    image: day02
    container_name: day02
    ports:
      - "2:4444/udp"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "echo \"Q\" | openssl s_client -dtls1_2 -connect localhost:4444 2>/dev/null | grep -q jnPpJf9enmLDJkaOhLTJ1Y3tn8lQpXjM || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    tty: true
  day03:
    image: day03
    container_name: day03
    ports:
      - "3:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:80/elf -O /tmp/elf || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  day04:
    image: day04
    container_name: day04
    ports:
      - "4:9000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/proxy.sh socks5 localhost 9000 curl --socks5 localhost:9000 localhost:9000/flag.txt | grep -q JAHr7BBNh0fp3IlbC2DItfWOV0CYIj3J || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  day05:
    image: day05
    container_name: day05
    ports:
      - "5:8443"
    restart: always
    read_only: true
  day06:
    image: day06
    container_name: day06
    ports:
      - "6:8080"
    read_only: true
    cap_drop:
      - NET_RAW
      - NET_BIND_SERVICE
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
  day07:
    image: day07
    container_name: day07
    ports:
      - "7:80"
    restart: always
  day08:
    image: day08
    container_name: day08
    ports:
      - "8:6801"
    healthcheck:
      test: ["CMD-SHELL", "echo -e \"\\x00\\x00\\x00\\x04\\x00\\x01\\x13\\x37\\x24\\x12\"| nc 127.0.0.1 6801 -q 1 | grep 'BRUM BRUM' || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  day09:
    image: day09
    container_name: day09
    ports:
      - "9:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -H \"Referer: /christmas_market\" -H \"From: santa@xmas.rip\" localhost:8000 | grep -q JuJiWZtTTQvVjDxF6qBB6F919hKappLb || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  day10:
    image: day10
    container_name: day10
    ports:
      - "10:80"
    restart: always
  day11:
    image: day11
    container_name: day11
    ports:
      - "11:4444"
  day12:
    image: day12
    container_name: day12
    ports:
      - "12:50051"
  day13:
    image: day13
    container_name: day13
    ports:
      - "13:80"
