version: '3'
services:
  nts:
    build: .
    volumes:
      - ./private:/etc/ssl/private:ro
    read_only: false
    # Testing only: network_mode: host
    ports:
      # HOST:CONTAINER
      - "15:4460/tcp"
      # UDP port is not necessary to solve the challenge:
      - "123:123/udp"