version: '3'
services:
  http3only:
    build: .
    volumes:
      - ./cert:/app/cert:ro
    read_only: true
    ports:
      # HOST:CONTAINER
      - "26:6121/udp"
    command: ["./http3only", "--flag", "ADD FLAG HERE"]